# Generated by Django 3.0.4 on 2022-12-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_orderinfo_order_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='order_time',
            field=models.DateTimeField(),
        ),
    ]
