# Generated by Django 3.0.4 on 2022-12-11 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20221211_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='order_time',
            field=models.DateTimeField(blank=True, default=datetime.date(1900, 1, 1), null=True, verbose_name='创建时间'),
        ),
    ]
