# Generated by Django 3.0.4 on 2022-12-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20221211_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='order_time',
            field=models.DateField(),
        ),
    ]
