# Generated by Django 3.0.4 on 2022-12-11 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_auto_20221211_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='order_time',
            field=models.DateField(blank=True, default=datetime.date(1900, 1, 1), null=True),
        ),
    ]
