# Generated by Django 3.0.4 on 2022-12-11 12:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_auto_20221211_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='order_time',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
